name: ayana_movies
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sizer: ^3.1.3
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dio: ^5.5.0+1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4
  connectivity_plus: ^6.0.5
  intl: ^0.20.2
  google_fonts: ^6.3.1
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.3
  bloc_test: ^9.1.5
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/ayana.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/i18n/
